FIX: add Namespace `Foam::` to `min/max()` calls in `applications/` dir          to avoid compile errors with clang/LLVM with `--offload-arch=`
    When using Clang packaged with ROCm, compilation fails due to ambiguous calls, for e.g.:

            In file included from overCompressibleInterDyMFoam.C:170:
            In file included from ../compressibleAlphaEqnSubCycle.H:45:
            In file included from ../../VoF/alphaEqn.H:101:
            ./alphaSuSp.H:29:34: error: call to 'max' is ambiguous
                    Sp[celli] -= dgdt[celli]/max(1.0 - alpha1[celli], 1e-4);
                                            ^~~
            /opt/rocm-6.0.0/llvm/lib/clang/17.0.0/include/__clang_hip_math.h:1345:8: note: candidate function
                    double max(double __x, double __y) { return fmax(__x, __y); }
                           ^
            /home/suyashtn/run/OpenFOAM/OpenFOAM-v2306/src/OpenFOAM/lnInclude/doubleFloat.H:55:1: note: candidate function
            MAXMINPOW(double, double, double)